# __Activity 5, Part 2__
## Rachel Nana, January 2019

In [1]:
import pandas as pd
import sklearn
import numpy as np

import pickle

__Importing Telco Sample Data__

In [2]:
telco_subset = pd.read_csv('telco_random_sample.csv');

In [3]:
telco_subset.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  3442-ZHHCC    Male              0      No         No      68          Yes   
1  9691-HKOVS  Female              0     Yes         No      55          Yes   
2  3621-CHYVB  Female              0     Yes         No      57           No   
3  6408-OTUBZ  Female              0      No         No      66          Yes   
4  2195-ZRVAX  Female              0     Yes         No      47          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0               Yes             DSL            Yes          Yes   
1               Yes             DSL            Yes          Yes   
2  No phone service             DSL            Yes           No   
3               Yes     Fiber optic            Yes          Yes   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0              Yes          No          No             Yes        One year   
1              Yes         Yes         Yes             Yes        One year   
2              Yes         Yes          No             Yes  Month-to-month   
3              Yes         Yes         Yes              No        One year   
4              Yes          No          No             Yes  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  
0              Yes    Credit card (automatic)           76.90         5023  
1              Yes           Electronic check           90.15      4916.95  
2              Yes  Bank transfer (automatic)           49.90       2782.4  
3              Yes  Bank transfer (automatic)          104.55      6779.05  
4              Yes           Electronic check           85.30      4045.65

__Data Prep__

In [4]:
from data_cleansing import TelcoPreprocessing
X = TelcoPreprocessing(telco_subset,[],X_only=True)

__Importing Model__

In [5]:
def pickle_load(name):
    PIK = str(name) + ".pickle"
    with open(PIK,"rb") as f:
        temp_item = pickle.load(f)
        return temp_item

In [6]:
pipe = pickle_load('telco_pipeline')

__Making Predictions__

In [7]:
from sklearn.metrics import roc_curve, roc_auc_score, log_loss
from matplotlib import pyplot as plt

In [8]:
# predicted class
predictions = pipe.predict(X)

# probability of each class
probs = pipe.predict_proba(X)

# probability of the predicted class
pred_probs = (predictions == 0)*probs[:,0] + (predictions == 1)*probs[:,1]

In [9]:
predictions[:5]

array([0, 0, 0, 0, 0], dtype=uint8)

In [10]:
probs[:5]

array([[0.90314897, 0.09685103],
       [0.92368181, 0.07631819],
       [0.90256973, 0.09743027],
       [0.87044629, 0.12955371],
       [0.58770103, 0.41229897]])

In [11]:
pred_probs[:5]

array([0.90314897, 0.92368181, 0.90256973, 0.87044629, 0.58770103])

In [12]:
# create DataFrame containing Predicted Value and Confidence
d = {'Prediction (Churn = Yes)': predictions.flatten(), 'Confidence': pred_probs.flatten()};
df = pd.DataFrame(d);
df.head()

Prediction (Churn = Yes)  Confidence
0                         0    0.903149
1                         0    0.923682
2                         0    0.902570
3                         0    0.870446
4                         0    0.587701

__Output__

In [13]:
telco_predictions = pd.merge(telco_subset, df, how='left', left_index=True, right_index=True)
telco_predictions

gender Partner Dependents  tenure PhoneService     MultipleLines  \
0       Male      No         No      68          Yes               Yes   
1     Female     Yes         No      55          Yes               Yes   
2     Female     Yes         No      57           No  No phone service   
3     Female      No         No      66          Yes               Yes   
4     Female     Yes         No      47          Yes                No   
5       Male      No         No      23          Yes                No   
6       Male      No         No       8          Yes               Yes   
7     Female      No         No       8          Yes                No   
8       Male     Yes         No      18          Yes               Yes   
9       Male     Yes        Yes       4          Yes                No   
10      Male     Yes        Yes      25          Yes                No   
11    Female      No         No      13          Yes                No   
12    Female     Yes         No      68          Yes               Yes   
13      Male     Yes         No      11          Yes                No   
14    Female     Yes        Yes      53           No  No phone service   
15    Female     Yes         No      22          Yes                No   
16    Female      No         No      36          Yes               Yes   
17    Female      No         No      16          Yes               Yes   
18      Male      No         No      14          Yes                No   
19    Female      No         No      13          Yes               Yes   
20      Male     Yes         No      51          Yes               Yes   
21    Female     Yes        Yes       4          Yes                No   
22      Male     Yes         No      59          Yes               Yes   
23      Male     Yes        Yes      70           No  No phone service   
24    Female      No         No       5          Yes               Yes   
25      Male     Yes        Yes      63          Yes               Yes   
26    Female      No         No      69          Yes               Yes   
27      Male      No         No       9          Yes                No   
28      Male      No         No       2          Yes                No   
29    Female      No         No      51          Yes               Yes   
...      ...     ...        ...     ...          ...               ...   
1731    Male      No         No      12          Yes               Yes   
1732  Female      No         No       3          Yes                No   
1733  Female     Yes        Yes      65          Yes               Yes   
1734  Female     Yes        Yes      48           No  No phone service   
1735  Female      No         No      41          Yes                No   
1736    Male     Yes        Yes      51          Yes                No   
1737    Male      No         No      67          Yes               Yes   
1738    Male      No        Yes      38          Yes               Yes   
1739    Male      No         No       1          Yes                No   
1740    Male      No         No      38          Yes                No   
1741  Female      No         No      37           No  No phone service   
1742    Male      No         No       1          Yes               Yes   
1743    Male      No         No       1          Yes                No   
1744    Male      No         No      69          Yes               Yes   
1745    Male      No         No      56          Yes                No   
1746    Male      No         No      27          Yes                No   
1747  Female      No         No      59          Yes                No   
1748  Female     Yes         No      37          Yes               Yes   
1749  Female      No         No       6           No  No phone service   
1750    Male     Yes         No      27          Yes                No   
1751    Male      No         No       3          Yes               Yes   
1752    Male     Yes         No       4          Yes               Yes   
1753    Ma

In [14]:
telco_predictions.to_csv('./telco_random_sample_predictions.csv', index=False)